#!/bin/sh
## postflight
##
## Not supported for flat packages.

pathToScript=$0
pathToPackage=$1
targetLocation=$2
targetVolume=$3

# load the launch agent
launchctl load /Library/LaunchAgents/com.wk.pdx.autointerface3.plist

# if a previous net state file exists, trash it
if [ -e /Users/.previous_netstate ]; then
	rm /Users/.previous_netstate
fi

# run the program
/usr/sbin/ai3.py


exit 0		## Success
exit 1		## Failure
